### ISSUE TITLE
Lab 2 shows progress bar

### ISSUE THREAD

**Issue by Johaning** [DS4PS/cpp-529-spr-2021#7]
When I knit my file, it shows multiple pages of a progress bar after my Step 1 code. Any suggestions for how to get rid of this? This is just the first bit, it continues on until it gets to 100%.

![image](https://user-images.githubusercontent.com/68923495/111921123-d6319800-8a60-11eb-9a23-91eaf6d097ca.png)

**Comment by RTrehern-ASU** [comment]
@Johaning ,
If you don't want it to appear when you knit the file into .html add the command "include=FALSE" at the start of your code chunk.  This is how it would look:

```{r, include=FALSE}
# insert your code here. 
```
Anything in that code chunk will not appear in the .html file.

**Comment by RTrehern-ASU** [comment]
@Johaning 
Sorry, that should look like " ```{r, include=FALSE} ... ```" but it appeared as a code chunk instead.
