### ISSUE TITLE
Error loading tmap

### ISSUE THREAD

**Issue by AprilPeck** [DS4PS/cpp-529-spr-2021#8]
I get the following error when I try to load tmap. I've tried uninstalling and reinstalling the package, but it's still erroring. It says it's installed fine, it's just when I try to load it that I get the error.

Error: package or namespace load failed for ‘tmap’ in inDL(x, as.logical(local), as.logical(now), ...): unable to load shared object 'C:/Users/apesm/Documents/R/win-library/4.0/raster/libs/x64/raster.dll': LoadLibrary failure: The specified procedure could not be found.

**Comment by Johaning** [comment]
Hopefully you've figured this out by now! When I got to the tmap commands I got an error message that told me I needed package "shinysj" and the error went away after I installed it. Hope this helps.
